### ISSUE TITLE
Monolog Switf_Mailer not working

### ISSUE THREAD

**Issue by rogeriolino** [php-pm/php-pm-httpkernel#62]
Hi,

I'm testing php-pm with my application and monolog has stopped sending me messages on error/exception (this same configuration works fine with php-cli [built-in server] / php-fpm).

```yml
monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            excluded_404s:
                - ^/
            handler:      grouped
        console:
            type:  console
            handler:      grouped
        grouped:
            type:    group
            members: [streamed, deduplicated]
        streamed:
            type:  stream
            path:  "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
        deduplicated:
            type:    deduplication
            handler: swift
        swift:
            type:       swift_mailer
            from_email: 'from-mail@address'
            to_email:   
                - 'to-mail@address1'
                - 'to-mail@address2'
            subject:    'Mail subject'
            level:      debug
            formatter:  monolog.formatter.html
            content_type: text/html
```
Is there a solution/workaround?

Regards

**Comment by marcj** [comment]
Do you get any errors?

**Comment by rogeriolino** [comment]
No errors.

**Comment by rogeriolino** [comment]
I've tried swiftmailer type as memory and spool. Sending message directly on controller works. Just on log fails.

**Tests**

Invoking Logger::error on controller action:

```php
$logger = $this->get('logger');
$logger->error('test');
```

*dev.log*

```
app.ERROR: test [] []
event.DEBUG: Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\DebugHandlersListener::configure". {"event":"kernel.request","listener":"Symfony\\Component\\HttpKernel\\EventListener\\DebugHandlersListener::configure"} []
```

Throwing exception on controller action:

```php
throw new \Exception('test');
```

*dev.log*

```
request.CRITICAL: Uncaught PHP Exception Exception: "test" at src/AppBundle/Controller/DefaultController.php line 15 {"exception":"[object] (Exception(code: 0): test at src/AppBundle/Controller/DefaultController.php:15)"} []
event.DEBUG: Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\DebugHandlersListener::configure". {"event":"kernel.request","listener":"Symfony\\Component\\HttpKernel\\EventListener\\DebugHandlersListener::configure"} []
```

**Comment by rogeriolino** [comment]
The issue is with **deduplicated** handler. Changed grouped to:

```yml
grouped:
    type:    group
    members: [streamed, swift]
```

Works, but I received 67 messages.

Now, I'll debug the deduplication handler type.
